version: '2.1'
services:
  baza:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "root_pass"
      MYSQL_DATABASE: "db_unos"
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "db_unos_pass"
    ports:
      - "43306:3306"
    volumes:
        - "./unos_mysql_data:/var/lib/mysql"
    healthcheck:
        test: ["CMD", "nc", "-z", "127.0.0.1", "3306"]
        interval: 2s
        timeout: 60s
        retries: 30